# Output Conversion with 3C Helper {#output-conversion}

## Understanding TLF Formats

RapTLR's `run_apdx()` function inserts TLFs into your Word document. To work properly, your outputs must be in **DOCX format**.

## What is 3C Helper?

3C Helper is a companion tool that converts various output formats to DOCX.\
The purpose of this tool is to convert your RTF outputs generated by SAS into DOCX and use them to create for each a bookmark and incorporate them into the TLR document.

## How to download 3C Helper

You can download 3C Helper on [this page](https://confluence.jnj.com/spaces/AHWD/pages/364845581/3C+Helper+v2.x+User+Guide) and click on *Download* in the sidebar.

## Converting your RTF outputs into DOCX

### Example from the TLR package

In the package we provided some dummy rtf outputs to practice.

You can use the function `import_RTFs()` to copy and create a clone folder of dummy rtf outputs in your working directory.

We are showing with the function `import_RTFs()` and 3C Helper how to convert your rtf outputs into docx outputs.

<video width="640" height="480" controls>

<source src="videos/02_package_rtf_to_docx.mp4" type="video/mp4">

</video>

### Example from SPACE

TO BE Populated

## Organizing Your TLF Folder

To keep things organized, we recommend to create a clear folder structure (see below).  
When you run run_apdx(), it will automatically create a new bookmarked subfolder wihtin the same directory of the .docx outputs and it will store the new bookmarked outputs there.
```         
TLR_project/
├── TLF_outputs/
│   ├── rtf/
│      ├── t_demographics_01.rtf
│      ├── t_efficacy_02.rtf
│      └── l_adverse_events_01.rtf
│   ├── docx/
│      ├── t_demographics_01.docx
│      ├── t_efficacy_02.docx
│      └── l_adverse_events_01.docx
│      ├── bookmarked/
│         ├── LKt_demographics_01.docx
│         ├── LKt_efficacy_02.docx
│         └── LKl_adverse_events_01.docx
├── TLR_shell/
│   ├── TLR_shell.docx
│   ├── TLR_final.docx
└── scripts/
    └── generate_tlr.R
```

## Quality Checks Before Processing

Before using `run_apdx()`, verify:

1.  **All files are rtf**
2.  **Files open correctly**
3.  **Consistent naming**

You're ready to move to appendix creation!